name: Go

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
        env:
          API_KEY_ID: "ewwewwe" #"${{ secrets.API_KEY_ID }}"
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: raynkami/uxti.finance
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
